### ISSUE TITLE
Does not compile on windows 11

### ISSUE THREAD

**Issue by nilesh-12** [vlang/ved#189]
```
$ v .
ved.v:871:49: error: `utf32_to_str_no_malloc` parameter `buf` is not `mut`, `mut` is not needed`
  869 |     }
  870 |     mut buf := [5]u8{}
  871 |     s := unsafe { utf32_to_str_no_malloc(code, mut &buf[0]) }
      |                                                    ^
  872 |
  873 |     // s := utf32_to_str(code)
```

**Comment by nilesh-12** [comment]
$ v -v
V 0.4.6 100b3b0

**Comment by spytheman** [comment]
Compilation is now working with latest V 0.4.8 c7ee45f .
